# This is a basic workflow to help you get started with Actions

name: Upgrade cluster node images

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 3 */15 * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upgrade-node:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Azure Login
        uses: Azure/login@v1
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}
       
      - name: Upgrade node images
        uses: Azure/cli@1.0.4
        with:
          # Specify the script here
          inlineScript:  az aks upgrade -g {myResourceGroup_1-7-21} -n {myAKSCluster} --node-image-only --yes
          
